### ISSUE TITLE
Seperate Sitemaps for subsites with different domain name?

### ISSUE THREAD

**Issue by Numkil** [studioespresso/craft-seo-fields#100]
I have subsite A with domainname "site1.demo.be" this is the primary site.

I have subsite B with domainname "site2.demo.be" this is not the primary site.

In the backend I only have access to 1 sitemap and the sections that are enabled for my primary site. I don't seem to be able to make a seperate sitemap for site2 with the sections enabled only for it.

Is this not supported yet or am I doing something wrong?

![Screenshot 2024-11-29 at 12 01 11](https://github.com/user-attachments/assets/3637a0bf-1107-46b1-b7ab-28a63d26cbe8)

**Comment by janhenckens** [comment]
There a settings for that through the configuration file, see the second part of this page https://studioespresso.github.io/craft-seo-fields/sitemap.html
