### ISSUE TITLE
sitemap.xml return 503 when not loggedin

### ISSUE THREAD

**Issue by jlachancekffein** [studioespresso/craft-seo-fields#11]
I use the plugin to generate a sitemap for a site.

Everything works correctly when the user is connected to the control panel.

However, if the user is not connected (example a robot), the url returns a 503 - Service unavailable error.

The url used is http://example.com/sitemap.xml

Is there a configuration to put in place to make functional?

Thanks for your help !

**Informations:**
Craft version : Craft CMS 3.2.9
Plugin version : 1.0.0

![Capture d’écran 2019-08-13 à 11 26 53](https://user-images.githubusercontent.com/24896469/62954387-50963280-bdbd-11e9-82ae-192d9758761f.png)

**Comment by janhenckens** [comment]
Hey there,

I can't reproduce the issue for an anonymous request on any of my test sites. Are you running any other plugins on the site?

**Comment by jlachancekffein** [comment]
Hi,

Here the composer require list :

    "craftcms/cms": "^3.0.0",
    "vlucas/phpdotenv": "^2.4.0",
    "nesbot/carbon": "^1.38",
    "firebase/php-jwt": "^5.0",
    "guzzlehttp/guzzle": "^6.3",
    "drewm/mailchimp-api": "^2.5",
    "craftcms/redactor": "^2.0.1",
    "spicyweb/craft-neo": "^2.3.5",
    "spicyweb/craft-fieldlabels": "^1.1.1",
    "chasegiunta/craft-jason": "^1.0.2",
    "verbb/field-manager": "^2.1.0",
    "craftcms/mailgun": "^1.4.2",
    "ostark/craft-async-queue": "^2.0",
    "lukeyouell/craft-hideadmin": "^1.0",
    "doublesecretagency/craft-cpbodyclasses": "^2.1.0",
    "mmikkel/incognito-field": "^1.1.1.1",
    "verbb/expanded-singles": "^1.0.7",
    "nystudio107/craft-imageoptimize": "^1.5.5",
    "studioespresso/craft-seo-fields": "^1.0",
    "supercool/tablemaker": "^2.0",
    "kffein/craft-koddein-fields": "^1.3"

**Comment by janhenckens** [comment]
Thanks for the extra info.

Could you try uninstalling the plugin and then try to access that url again? Does it still throw the 503?

**Comment by janhenckens** [comment]
Check. Could you try changing your sitemap settings? Maybe try just enabling 1 section (a homepage single or something like that) and see it still crashes?

**Comment by jlachancekffein** [comment]
Still crash !

**Comment by jlachancekffein** [comment]
It's really weird because in SeoFields.php 

```
if ($shouldRender) {
                    $event->rules = array_merge($event->rules, [
                        'sitemap.xml' => 'seo-fields/sitemap/render',
                        'sitemap_<siteId:\d>_<type:(entry|product|category)>_<sectionId:\d>_<handle:.*>.xml' => 'seo-fields/sitemap/detail'
                    ]);
                }
```

The $shouldRender condition is met and the rules is add to the listed rules...

For an unknown reason, if i'm not connected to CP, the rules do not apply....

**Comment by janhenckens** [comment]
Would it be possible for you to send me the composer.json, composer.lock and the database you're using right now? (wetransfer to jan@studioespresso.co) - Kind of hard to debug this without your actual content and I can't reproduce it here.

**Comment by janhenckens** [comment]
I reinstalled the plugin on my test install and now I'm having the same issue. Diving in :)
I'll try to get back to you asap!

**Comment by jlachancekffein** [comment]
Not a good news but at least it will be easier for you to find a solution. :)

Thank you for the follow up.

**Comment by janhenckens** [comment]
Just published an update that should address this. Could you give it a try and let me know if it works now?
Thanks!

**Comment by jlachancekffein** [comment]
Thank you so much.

Now it work without problems.

**Comment by janhenckens** [comment]
Great! Let me know if you run into anything else, happy to help out :)
