### ISSUE TITLE
Release 1.0.2 is broken

### ISSUE THREAD

**Issue by jlachancekffein** [studioespresso/craft-seo-fields#16]
Your last release (1.0.2) is broken. It is now impossible to edit all the entries in all our CMS (live website).

![image](https://user-images.githubusercontent.com/24896469/67951200-71527500-fbc1-11e9-9bbd-5782028f1d24.png)

The problem is this code: src/craftCMS/vendor/studioespresso/craft-seo-fields/src/SeoFields.php (line 268)

```
Craft::$app->getView()->hook('cp.entries.edit.details', function (array &$context) {
            $handle = $this->getSettings()->fieldHandle;
            if ($context['entryId']) {
                if ($context['entry']->$handle instanceof SeoFieldModel) {
                }
            }
        });
```

We have to fix it on all our live website inside vendor by commenting this code. How this useless code can be in an official release ?

I have some expectations of a 49$ plugin. Can you please test your release before push it to composer ?

Sorry but I raised one issue a day in the last three days. For a free plugin I can understand but not for a 49$.

Thank you !

**Comment by janhenckens** [comment]
Hey there. Very sorry about that, just released a fix for this.

There are a couple of free SEO alternatives, you're welcome to switch to those if you wish. 
I also see you haven't purchased a license for the plugin yet and I apologize if this error will stop you from doing that.

Let me know if there is anything else I can help you with.
