### ISSUE TITLE
Sitemap lastmod node invalid datetime format

### ISSUE THREAD

**Issue by jlachancekffein** [studioespresso/craft-seo-fields#17]
The value of the lastmod of the sitemap.xml is invalid. ``` ('Y-m-d h:m:s') ```

https://www.sitemaps.org/protocol.html
https://www.w3.org/TR/NOTE-datetime

I change it to ```('Y-m-d')``` to make it valid by google search console : https://search.google.com/search-console/

**Comment by janhenckens** [comment]
Fixed in 1.0.4.
