### ISSUE TITLE
Crash on sitemap settings

### ISSUE THREAD

**Issue by janhenckens** [studioespresso/craft-seo-fields#21]
yii\base\ErrorException: Trying to get property 'siteSettings' of non-object in /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/studioespresso/craft-seo-fields/src/services/SitemapService.php:304
Stack trace:
#0 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/data/sites/web...', 304)
#1 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/studioespresso/craft-seo-fields/src/services/SitemapService.php(304): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/data/sites/web...', 304, Array)
#2 [internal function]: studioespresso\seofields\services\SitemapService->studioespresso\seofields\services\{closure}(10)
#3 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/studioespresso/craft-seo-fields/src/services/SitemapService.php(311): array_filter(Array, Object(Closure), 2)
#4 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/studioespresso/craft-seo-fields/src/services/SitemapService.php(56): studioespresso\seofields\services\SitemapService->_shouldRenderEntries(Array)
#5 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/studioespresso/craft-seo-fields/src/SeoFields.php(218): studioespresso\seofields\services\SitemapService->shouldRenderBySiteId(Object(craft\models\Site))
#6 [internal function]: studioespresso\seofields\SeoFields->studioespresso\seofields\{closure}(Object(craft\events\RegisterUrlRulesEvent))
#7 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\RegisterUrlRulesEvent))
#8 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\web\\UrlMa...', 'registerSiteUrl...', Object(craft\events\RegisterUrlRulesEvent))
#9 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/src/web/UrlManager.php(329): yii\base\Component->trigger('registerSiteUrl...', Object(craft\events\RegisterUrlRulesEvent))
#10 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/src/web/UrlManager.php(98): craft\web\UrlManager->_getRules()
#11 [internal function]: craft\web\UrlManager->__construct(Array)
#12 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#13 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\UrlMa...', Array, Array)
#14 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\UrlMa...', Array, Array)
#15 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#16 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('urlManager', true)
#17 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/src/web/Application.php(340): yii\base\Module->get('urlManager', true)
#18 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/base/Application.php(571): craft\web\Application->get('urlManager')
#19 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2-debug/src/Module.php(270): yii\base\Application->getUrlManager()
#20 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/src/web/Application.php(420): yii\debug\Module->bootstrap(Object(craft\web\Application))
#21 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/src/web/Application.php(104): craft\web\Application->debugBootstrap()
#22 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#23 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#24 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/src/web/Application.php(91): yii\base\Application->__construct(Array)
#25 [internal function]: craft\web\Application->__construct(Array)
#26 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#27 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#28 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#29 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/bootstrap/bootstrap.php(245): yii\BaseYii::createObject(Array)
#30 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/vendor/craftcms/cms/bootstrap/web.php(51): require('/data/sites/web...')
#31 /data/sites/web/mobschlivestatikbe/subsites/mobsch.live.statik.be/public/index.php(22): require('/data/sites/web...')
#32 {main}

**Comment by carolineboeykens** [comment]
Hi Jan,
I had this issue too when I deleted a section that was used in the sitemap. I tried clearing the sitemap caches but this didn't help. When I resaved the sitemap, the error was gone.

Can you maybe resave the sitemap when deleting a section?

**Comment by janhenckens** [comment]
Finally got around to fixing this one! Released in 1.0.6.
