### ISSUE TITLE
Focuspoint for OG Image

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-seo-fields#23]
Could you make the focus point from the asset library work with your SEO OG image?

![Screen Shot 2020-02-25 at 16 35 38](https://user-images.githubusercontent.com/42932673/75262680-281bd600-57ed-11ea-80a1-88f6acecd7b3.png)

**Comment by janhenckens** [comment]
Fixed [here](https://github.com/studioespresso/craft-seo-fields/commit/3cfac72b8407191626340f80cbbd0235e12d86e2).

To get the fix early, change your studioespresso/craft-seo-fields requirement in composer.json to:

```
"require": {
  "studioespresso/craft-seo-fields": "dev-develop#3cfac72b8407191626340f80cbbd0235e12d86e2 as 2.0.0",
  "...": "..."
}
```
Then run composer update. Note that this will also get you the entire 2.0.0 update with redirects & 404 tracking.
