### ISSUE TITLE
Sitemap settings has no site switch

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-seo-fields#24]
The sitemap settings has no site switch but the settings are saved per site. I save the sitemap for the NL site and if I changes the url to `/fr` the settings were not saved for this site.

<img width="1302" alt="Screen Shot 2020-06-05 at 11 32 55" src="https://user-images.githubusercontent.com/42932673/83861250-a3f8b900-a720-11ea-87b1-40e40adefa28.png">

**Comment by janhenckens** [comment]
This is the intended behavior. You can force sitemaps per site through a config setting, see the docs for that [here](https://studioespresso.github.io/craft-seo-fields/sitemap.html#multisite)
