### ISSUE TITLE
CraftCMS 3.5.0 - Sitemap : Integrity constraint violation: 1052 Column 'enabled' in where clause is ambiguous

### ISSUE THREAD

**Issue by jlachancekffein** [studioespresso/craft-seo-fields#25]
With Craft 3.5.0, an error is raised while viewing the sitemap.

The 1st level listing works correctly. Ex: [host] /sitemap.xml

But the detail of a sitemap causes an error. Ex: [host] /sitemap_2_entry_1_single_homepage.xml

To fix the problem, I had to adjust the SQL query directly in the vendor folder: src/craftCMS/vendor/studioespresso/craft-seo-fields/src/services/SitemapService.php

**BEFORE**
```php
$siteEntries =
                (new Query())->select(['siteId', 'uri', 'language'])
                    ->from('{{%elements_sites}}')
                    ->leftJoin('{{sites}}', 'sites.id = elements_sites.siteId')
                    ->where('[[elementId]] = ' . $entry->id)
                    ->andWhere('enabled = true')
                    ->all();
```

**AFTER**
```php
$siteEntries =
                (new Query())->select(['elements_sites.siteId', 'elements_sites.uri', 'sites.language'])
                    ->from('{{%elements_sites}}')
                    ->leftJoin('{{sites}}', 'sites.id = elements_sites.siteId')
                    ->where('[[elementId]] = ' . $entry->id)
                    ->andWhere('sites.enabled = true')
                    ->all();
```

**Comment by janhenckens** [comment]
Thanks for catching that! I think the enabled should come from element_sites though, not sites. Sites can't be disabled right now and here we're checking the status of the current entry, not the site.

I'll release a fix for this tonight!

**Comment by janhenckens** [comment]
Release is out!
