### ISSUE TITLE
Sitemap section/category options should be saved inside project-config

### ISSUE THREAD

**Issue by jlachancekffein** [studioespresso/craft-seo-fields#27]
At this time, changes made to the sitemap (inside cp) are not saved in project-config. So, we have to manually repeat this process on each server.

Ideally, the configuration should be saved with project-config in order to have the same configuration on each remote server.

Versions :

craftcms/cms: 3.5.10.1
studioespresso/craft-seo-fields: 1.0.9

**Comment by jlachancekffein** [comment]
Is this plugin still active?

**Comment by janhenckens** [comment]
Sure is @jlachancekffein. It's just that moving the entire plugin config to project config is quite a bit of work and I haven't been able to continue working on it. I'll let you know when I have an update out that fixes this.

**Comment by janhenckens** [comment]
Hey @jlachancekffein, I had a look at this (and got halfway through implementing it) and there might be an issue here. 

The way the plugins default site data is structured, the default descriptions, robots and sitemap data are saved together, meaning that all those would end up on the project config. But that also has the default image. Which is probably something you'll want to set on the live server. Saving on the live server will change the project config, but a subsequent deploy will overwrite that change.... Not good.

Curious for your thoughts on this. Are you just looking for the sitemap settings to be in sync?
