### ISSUE TITLE
Error when deleting section

### ISSUE THREAD

**Issue by janhenckens** [studioespresso/craft-seo-fields#48]
`"Argument 1 passed to studioespresso\\seofields\\SeoFields::studioespresso\\seofields\\{closure}() must be an instance of craft\\events\\SectionEvent, instance of craft\\events\\EntryTypeEvent given"
`

**Comment by carolineboeykens** [comment]
@janhenckens , is there a fix for this issue? I still have the bug on a new install

`{"error":"Argument 1 passed to studioespresso\\seofields\\SeoFields::studioespresso\\seofields\\{closure}() must be an instance of craft\\events\\SectionEvent, instance of craft\\events\\EntryTypeEvent given","exception":"TypeError","file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/studioespresso/craft-seo-fields/src/SeoFields.php","line":324,"trace":[{"function":"studioespresso\\seofields\\{closure}","class":"studioespresso\\seofields\\SeoFields","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/yiisoft/yii2/base/Event.php","line":312,"function":"call_user_func"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/yiisoft/yii2/base/Component.php","line":642,"function":"trigger","class":"yii\\base\\Event","type":"::"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/Sections.php","line":1412,"function":"trigger","class":"yii\\base\\Component","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/base/ApplicationTrait.php","line":1681,"function":"handleDeletedEntryType","class":"craft\\services\\Sections","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/ProjectConfig.php","line":1189,"function":"craft\\base\\{closure}","class":"craft\\web\\Application","type":"->"},{"function":"handleChangeEvent","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/yiisoft/yii2/base/Component.php","line":633,"function":"call_user_func"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/ProjectConfig.php","line":746,"function":"trigger","class":"yii\\base\\Component","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/ProjectConfig.php","line":521,"function":"_processConfigChangesInternal","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/ProjectConfig.php","line":537,"function":"set","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/Sections.php","line":1342,"function":"remove","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/Sections.php","line":829,"function":"deleteEntryType","class":"craft\\services\\Sections","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/services/Sections.php","line":801,"function":"deleteSection","class":"craft\\services\\Sections","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/controllers/SectionsController.php","line":203,"function":"deleteSectionById","class":"craft\\services\\Sections","type":"->"},{"function":"actionDeleteSection","class":"craft\\controllers\\SectionsController","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/yiisoft/yii2/base/InlineAction.php","line":57,"function":"call_user_func_array"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/yiisoft/yii2/base/Controller.php","line":178,"function":"runWithParams","class":"yii\\base\\InlineAction","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/yiisoft/yii2/base/Module.php","line":552,"function":"runAction","class":"yii\\base\\Controller","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/web/Application.php","line":287,"function":"runAction","class":"yii\\base\\Module","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/web/Application.php","line":596,"function":"runAction","class":"craft\\web\\Application","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/craftcms/cms/src/web/Application.php","line":266,"function":"_processActionRequest","class":"craft\\web\\Application","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/vendor/yiisoft/yii2/base/Application.php","line":384,"function":"handleRequest","class":"craft\\web\\Application","type":"->"},{"file":"/Users/carolineboeykens/Documents/Sites/pocweb/public/index.php","line":23,"function":"run","class":"yii\\base\\Application","type":"->"}]}`

**Comment by janhenckens** [comment]
Hmm, looks like I forgot to release this. Will fix right away!

**Comment by janhenckens** [comment]
Fixed in 2.0.5!
