### ISSUE TITLE
Error when applying project config

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-seo-fields#55]
`Status: error`

`Response: {"error":"Attempt to read property \"id\" on null","exception":"yii\\base\\ErrorException","file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/studioespresso/craft-seo-fields/src/services/SitemapService.php","line":179,"trace":[{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/ErrorHandler.php","line":84,"function":"handleError","class":"yii\\base\\ErrorHandler","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/studioespresso/craft-seo-fields/src/services/SitemapService.php","line":179,"function":"handleError","class":"craft\\web\\ErrorHandler","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/studioespresso/craft-seo-fields/src/SeoFields.php","line":310,"function":"clearCacheForElement","class":"studioespresso\\seofields\\services\\SitemapService","type":"->"},{"function":"studioespresso\\seofields\\{closure}","class":"studioespresso\\seofields\\SeoFields","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Event.php","line":312,"function":"call_user_func"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Component.php","line":642,"function":"trigger","class":"yii\\base\\Event","type":"::"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/Elements.php","line":1724,"function":"trigger","class":"yii\\base\\Component","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/Sections.php","line":1391,"function":"deleteElement","class":"craft\\services\\Elements","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/base/ApplicationTrait.php","line":1681,"function":"handleDeletedEntryType","class":"craft\\services\\Sections","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php","line":1199,"function":"craft\\base\\{closure}","class":"craft\\web\\Application","type":"->"},{"function":"handleChangeEvent","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Component.php","line":633,"function":"call_user_func"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php","line":765,"function":"trigger","class":"yii\\base\\Component","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php","line":1189,"function":"_processConfigChangesInternal","class":"craft\\services\\ProjectConfig","type":"->"},{"function":"handleChangeEvent","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Component.php","line":633,"function":"call_user_func"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php","line":765,"function":"trigger","class":"yii\\base\\Component","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php","line":1307,"function":"_processConfigChangesInternal","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/services/ProjectConfig.php","line":594,"function":"_applyChanges","class":"craft\\services\\ProjectConfig","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/controllers/ConfigSyncController.php","line":59,"function":"applyYamlChanges","class":"craft\\services\\ProjectConfig","type":"->"},{"function":"actionApplyYamlChanges","class":"craft\\controllers\\ConfigSyncController","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/InlineAction.php","line":57,"function":"call_user_func_array"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Controller.php","line":178,"function":"runWithParams","class":"yii\\base\\InlineAction","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Module.php","line":552,"function":"runAction","class":"yii\\base\\Controller","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/Application.php","line":293,"function":"runAction","class":"yii\\base\\Module","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/Application.php","line":602,"function":"runAction","class":"craft\\web\\Application","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/craftcms/cms/src/web/Application.php","line":272,"function":"_processActionRequest","class":"craft\\web\\Application","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/vendor/yiisoft/yii2/base/Application.php","line":384,"function":"handleRequest","class":"craft\\web\\Application","type":"->"},{"file":"/data/sites/web/kulstslivestatikbe/subsites/kulsts.staging.statik.be/public/index.php","line":23,"function":"run","class":"yii\\base\\Application","type":"->"}]}`

**Comment by janhenckens** [comment]
Which Craft version are you seeing this error on? Should be working on the latest 3.7.x version.

**Comment by janhenckens** [comment]
@carolineboeykens Which Craft version are you seeing this error on? Should be working on the latest 3.7.x version with the latest version of the plugin.

**Comment by carolineboeykens** [comment]
`"craftcms/cms": "3.7.38"`
`"studioespresso/craft-seo-fields": "2.0.6"`

I deleted the section local, which worked, but when the project-config/apply on staging was triggered, the error appeared

**Comment by janhenckens** [comment]
Running garbage collection before applying the config fixed this issue.
