### ISSUE TITLE
[Craft 4] Error when trying to open Robots.txt and Sitemap.xml

### ISSUE THREAD

**Issue by HannahDeWachter** [studioespresso/craft-seo-fields#60]
When clicking on the Robots.txt or Sitemap.xml tab in the backend I recieve following error: `Type of studioespresso\seofields\controllers\RobotsController::$allowAnonymous must be array|int|bool (as in class craft\web\Controller)` and `Type of studioespresso\seofields\controllers\SitemapController::$allowAnonymous must be array|int|bool (as in class craft\web\Controller)` respectively. This is not the case when I click on Meta, 404's and Redirects.

**Versions :**
craftcms/cms: 4.0.2
studioespresso/craft-seo-fields: 3.0.2

**Comment by janhenckens** [comment]
Thanks for reporting this @HannahDeWachter, fix is out in 3.0.3.
