### ISSUE TITLE
Twitter and Facebook Image does not work

### ISSUE THREAD

**Issue by HannahDeWachter** [studioespresso/craft-seo-fields#64]
I try to override the Facebook and Twitter image with an other image. However, they return empty `facebookImage: ""`.

Craft version: 4.2.3
Plugin version: 3.0.5

**Comment by janhenckens** [comment]
Still haven't found a solution for this, hoping this will help me along https://github.com/craftcms/cms/discussions/13945

**Comment by janhenckens** [comment]
This one is (finally) fixed in version 4.0.0. You can find the documentation [here](https://studioespresso.github.io/craft-seo-fields/templating.html#overwriting-field-values)
