### ISSUE TITLE
Bug in permissions

### ISSUE THREAD

**Issue by carolineboeykens** [studioespresso/craft-seo-fields#65]
Hi

We set the permissions to only 404's and Redirects but when the users clicks the SEO Fields tab in the side bar he gets redirected to the meta tab although he has no permissions here.

Can you check this please?

![Screenshot 2022-10-12 at 10 01 07](https://user-images.githubusercontent.com/42932673/195285681-1da33b12-ca6e-4041-86e0-4240b21287aa.png)

![Screenshot 2022-10-12 at 10 01 47](https://user-images.githubusercontent.com/42932673/195285692-d842242f-32ea-4c8f-a14d-f32fe68697d2.png)

**Comment by janhenckens** [comment]
Thank for reporting this @carolineboeykens, will check!

**Comment by janhenckens** [comment]
Fixed in 3.1.1
