### ISSUE TITLE
sourceMatch stays NULL in database table

### ISSUE THREAD

**Issue by HannahDeWachter** [studioespresso/craft-seo-fields#68]
Redirects do not work because the sourceMatch field in the database stays "NULL" instead of "path".
<img width="1268" alt="Screenshot 2022-12-15 at 10 44 24" src="https://user-images.githubusercontent.com/55497252/207826788-c5098673-5e1b-44ba-806e-c73f9b4a5962.png">

Version: 3.1.2

**Comment by janhenckens** [comment]
Fix for that is ready on develop, should be released next week!

**Comment by janhenckens** [comment]
This was fixed in 3.2.0, which is now available!
