### ISSUE TITLE
Sitemap for products doesn't gets created in case of multisites

### ISSUE THREAD

**Issue by alpine-digital** [studioespresso/craft-seo-fields#70]
Hi Jan

I've created a pull request to fix the following issue: in case of multisites, the sitemap doesn't gets created for the site that is not the first site. The foreach gets interrupted after the first iteration and either returns true or false. The other iterations need to be handled to create the correct sitemap.

The pull request: https://github.com/studioespresso/craft-seo-fields/pull/69

Thanks!

**Comment by janhenckens** [comment]
Thanks for catching that, this seems to fix that.
Merge to develop for now, I'm finishing up another feature for the plugin in the next 2 weeks.

Let me know if you need this sooner, I can always make a separate release for it.

**Comment by alpine-digital** [comment]
Hi Jan
I was waiting for the new release, but is it possible to create a seperate release for the fix?
Thanks!

**Comment by janhenckens** [comment]
Sorry about the delay, the fix is out in today's release (version 3.2.1)
