### ISSUE TITLE
Admin screen for redirects is inaccessible in multisite environment

### ISSUE THREAD

**Issue by axis80** [studioespresso/craft-seo-fields#72]
Steps to reproduce:

1. Have a multisite environment with Site A, Site B, Site C.
2. Click the SEO Fields -> Redirects link in the left column of the admin.
3. Note that Site A is selected by default in the site switcher menu near the top of the page.
4. If you change to Site B, you get redirected to the "404's" screen for Site A.

**Comment by axis80** [comment]
BTW, Craft CMS version is 3.8.8.  Let me know if you need me to send you any sort of debug logs.

**Comment by janhenckens** [comment]
Hey @axis80, I've tried this on my Craft 3 test setup but I'm able to switch between sites without issue. Could you maybe make a screen recording where you also have the network tab of the inspector open so we can debug the requests?

**Comment by janhenckens** [comment]
Closing this for now, feel free to reopen is this is still current
