### ISSUE TITLE
Creating a new redirect causes Internal Server Error in multisite environment

### ISSUE THREAD

**Issue by axis80** [studioespresso/craft-seo-fields#73]
Steps to reproduce:

1. Have a multisite environment with Site A, Site B, Site C.
2. Click the SEO Fields -> Redirects link in the left column of the admin.
3. Note that Site A is selected by default in the site switcher menu near the top of the page.
4. Click the button to create a new redirect.
5. You get Internal Server Error - Server Error

Craft CMS version is 3.8.8.  Here's the money line from the error log:

[error][Twig\Error\SyntaxError] Twig\Error\SyntaxError: Unknown "d" function. Did you mean "head", "date", "round", "random", "include", "dataUrl", "endBody", "beginBody", "hiddenInput", "getHeadHtml", "getSeoFields", "redirectInput", "formieInclude", "formieSiteInclude", "formiePluginInclude", "renderObjectTemplate"? in /var/www/vhosts/www.example.com/craft/vendor/studioespresso/craft-seo-fields/src/templates/_redirect/_entry.twig:24

**Comment by axis80** [comment]
BTW I'm not sure this has anything to do with our Craft installation being a multisite one.

**Comment by janhenckens** [comment]
Hery @axis80, this is definitely an issue with the plugin, which I can fix.

I'm currently without internet access at home so I won't be able to get back to you on this before the end of next week. I'll add both your issues (this one and #72) to the backlog for an update to the Craft 3 version.

**Comment by axis80** [comment]
Hi @janhenckens, and thank you for your reply.  We will definitely welcome a fix, but we are not in a big hurry for it as we are mostly using the other features of the plugin at the moment.  So, whenever you can get to it will be fine with us :-)

**Comment by janhenckens** [comment]
Hey @axis80 , the fix for this is out in 2.0.11.
