### ISSUE TITLE
Meta tag Twitter image

### ISSUE THREAD

**Issue by HannahDeWachter** [studioespresso/craft-seo-fields#76]
Craft version: 3.8.13
Plugin version: 2.0.11

I get an error when no Twitter Image is provided. 

> Impossible to access an attribute ("url") on a boolean variable ("").

In templates/_meta.twig:
```
{% if ogImage %}
    <meta name="twitter:image" content="{{ meta.getTwitterImage().url }}" />
{% endif %}
```

Here you do a check to see if there is an ogImage but then use the TwitterImage instead. When changing getTwitterImage() to getOgImage() the error is gone.
Can you please fix this for Craft 3.

**Comment by janhenckens** [comment]
Hey @HannahDeWachter, since this is for Craft 3, are you still looking for a fix for this or can I close it for now.

Thanks for letting me know :)
