### ISSUE TITLE
Permission for user group to access Meta

### ISSUE THREAD

**Issue by LauraStatik** [studioespresso/craft-seo-fields#77]
When I change the permissions of a specific user group (content managers) to access "Meta" of SEO Fields, this is not shown for them. The other ones (404's, redirects, ...) are shown when allowed in the permissions.

Craft CMS version 4.4.13
Plugin version 3.2.1

**Comment by janhenckens** [comment]
Fixed in 3.3.0

**Comment by janhenckens** [comment]
Found the issue here, I'll ping you when the next release is ready @LauraStatik

**Comment by janhenckens** [comment]
Released in 3.3.1
