### ISSUE TITLE
[STU-73] Admin control "Sitemap" returns Twig Runtime Error

### ISSUE THREAD

**Issue by petenice** [studioespresso/craft-seo-fields#84]
Clicking on SEO -> Sitemap.xml returns page with error

"Impossible to access an attribute ("id") on a null variable."

Screenshot here:
[https://www.screencast.com/t/EApqvTAdD](https://www.screencast.com/t/EApqvTAdD)

**Application Info**
PHP version	8.0.25
OS version	Darwin 22.5.0
Database driver & version	MySQL 8.0.29
Image driver & version	GD 8.0.25
Craft edition & version	Craft Pro 4.5.6.1
Yii version	2.0.48.1
Twig version	v3.4.3
Guzzle version	7.8.0

**Plugins**
Batch Actions	1.3.0
CKEditor	3.6.0
Code Field	4.0.10
Colour Swatches	4.3.0
Control Panel CSS	2.6.0
Feed Me	5.2.0
Google Custom Search	2.1.4
Navigation	2.0.21
Neo	3.9.5
Retcon	2.7.3
Retour	4.1.13
SEO Fields	3.3.3
Sprig	2.7.2
Typed link field	2.1.5
Typogrify	4.0.1

**Modules**
codeeditor	nystudio107\codeeditor\CodeEditor
verbb-base	verbb\base\Base
sprig-core	putyourlightson\sprig\Sprig

<sub>[STU-73](https://linear.app/studio-espresso/issue/STU-73/admin-control-sitemap-returns-twig-runtime-error)</sub>

**Comment by janhenckens** [comment]
Hey @petenice, this was fixed in [3.3.4](https://github.com/studioespresso/craft-seo-fields/blob/develop/CHANGELOG.md#334---2023-10-14), could try updating to that version?

**Comment by petenice** [comment]
SUCCESS! Thank you!

**Comment by janhenckens** [comment]
Thanks for confirming!
