### ISSUE TITLE
[STU-86] Og-fields are not using correct fallback when entry og-fields are not set

### ISSUE THREAD

**Issue by AntonLecock** [studioespresso/craft-seo-fields#86]
null

<sub>[STU-86](https://linear.app/studio-espresso/issue/STU-86/og-fields-are-not-using-correct-fallback-when-entry-og-fields-are-not)</sub>

**Comment by janhenckens** [comment]
Fixed in 3.3.7, can you update and try @AntonLecock? Feel free to reopen should you still see the issue!
