### ISSUE TITLE
Default settings error if not multisite

### ISSUE THREAD

**Issue by Mathias-Syversen** [studioespresso/craft-seo-fields#91]
When trying to access the default settings for the plugin at /admin/seo-fields/defaults/settings, you get an error that the site variable is not available, if I set the site in the url with &site=default, it works.

The plugin should probably default to the default site if no site is provided in the url.

**Comment by janhenckens** [comment]
Hey @Mathias-Syversen, which version of the plugin & craft are you running? 

I released an update that touches on this yesterday but I can't reproduce your issue on a Craft install with only 1 site and the latest version of the plugin.
