### ISSUE TITLE
issue with custom fieldHandle

### ISSUE THREAD

**Issue by kffein-david** [studioespresso/craft-seo-fields#94]
When using custom fieldHandle to name an seo field, then there is an error in SitemapService.php

Steps to reproduce:

1- give your seo field the handle "commons_seo"

2- in config/seo-fields.php specify the custom handle:
```
return [
	"fieldHandle" => "commons_seo",
];
```

3- check you sitemap ( not the sitemap index but a detailled one)

result:
**Getting unknown property: craft\elements\Entry::seo** 

coming from SitemapService.php

```
if ($entry->**seo**->allowIndexing === 'no') {
     continue;
}
```
            
            
CraftCMS version: 5.1.4
Plugin version: 5.0.0-beta.1

**Comment by janhenckens** [comment]
Hey @kffein-david

Thanks for reporting that! Looks like I'm not taking the plugin handle into account correctly there. I'll try to have a fix out by the end of the week!

**Comment by kffein-david** [comment]
Thank you


*David Guillemin* (il/he)
President and CEO | Président-directeur-général
____

[image: KFFEIN] <https://kffein.com/>

T. 514.897.2991 <5148972991,1081> #1081
7236, rue Waverly, #303
Montréal, QC H2R 0C2
kffein.com


Le mer. 22 mai 2024 à 02:46, Jan Henckens ***@***.***> a
écrit :

**Comment by kffein-david** [comment]
Hi Jan,

It works.


Thank you for your quick response

*David Guillemin* (il/he)
President and CEO | Président-directeur-général
____

[image: KFFEIN] <https://kffein.com/>

T. 514.897.2991 <5148972991,1081> #1081
7236, rue Waverly, #303
Montréal, QC H2R 0C2
kffein.com


Le mer. 22 mai 2024, à 14 h 05, Jan Henckens ***@***.***> a
écrit :
